### ISSUE TITLE
Migrate to Manifest V3

### ISSUE THREAD

**Issue by perceptron8** [perceptron8/pinky.ext#68]
## Readme
* https://groups.google.com/a/chromium.org/d/msg/chromium-extensions/hG6ymUx7NoQ/TiAe0gI5AQAJ
    - https://developer.chrome.com/extensions/migrating_to_manifest_v3
    - https://developer.chrome.com/extensions/migrating_to_service_workers
* https://discourse.mozilla.org/t/migrating-to-manifest-v3/35784
    - https://blog.mozilla.org/addons/2019/09/03/mozillas-manifest-v3-faq/

## Todo
- [x] Migrate request modification logic to chrome.declarativeNetRequest rules.
- [x] Replace the webRequestBlocking permission with declarativeNetRequest.
- [x] Remove unnecessary permissions.

## Timeline
- February 4, 2020: Chrome 80 Stable released.

**Comment by perceptron8** [comment]
Still not quite ready?

> This API is in beta. It is only available to Chrome users on the beta channel and dev channel.
https://developer.chrome.com/extensions/declarativeNetRequest

**Comment by perceptron8** [comment]
Firefox doesn't support V3 yet.

**Comment by perceptron8** [comment]
Support is now provided for the [declarativeNetRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest) API ([Firefox bug 1782685](https://bugzil.la/1782685)).
